```mermaid
graph LR
    C16[assets-constructor<br/><small>size=3579 cohesion=0.53</small>]
    C14[novelist-brain-dict<br/><small>size=1771 cohesion=0.27</small>]
    C23[tests-tick<br/><small>size=1038 cohesion=0.26</small>]
    C15[web-api<br/><small>size=73 cohesion=0.29</small>]
    C24[tools-draw<br/><small>size=73 cohesion=0.24</small>]
    C22[views-fmt<br/><small>size=64 cohesion=0.02</small>]
    C18[social-tone<br/><small>size=59 cohesion=0.07</small>]
    C19[composables-use<br/><small>size=27 cohesion=0.08</small>]
    C20[stores-fetch<br/><small>size=26 cohesion=0.31</small>]
    C13[lin-yi-context<br/><small>size=17 cohesion=0.05</small>]
    C21[utils-download<br/><small>size=6 cohesion=0.11</small>]
    C17[src-drawer<br/><small>size=5 cohesion=0.00</small>]
```